#!/bin/bash

set -o nounset
set -o errexit

MOMC=${MOMC-"momc"}
MOMPrinter=${MOMPrinter-"MOMPrinter"}
TMP_DIR=$(mktemp -d /tmp/datamodelconvXXXXXX)
TMP_MOM="$TMP_DIR/out.mom"
INPUT_MODEL_DIR=

set +o nounset
if [[ -z "$1" ]]; then
    echo "No xcdatamodeld file given" >&2
    exit 1
elif [[ -d "$1" ]]; then
    INPUT_MODEL_DIR="$1"
else # elements file is given, copy to a temp directory
    INPUT_MODEL_DIR="$TMP_DIR/in.xcdatamodel"
    mkdir -p "$INPUT_MODEL_DIR"
    cp "$1" "$INPUT_MODEL_DIR/elements"
fi
set -o nounset

"$MOMC" "$INPUT_MODEL_DIR" "$TMP_MOM"
"$MOMPrinter" "$TMP_MOM"
rm "$TMP_MOM"

exit 0

